import { ROLES } from "./roles";

export const PAGE_PERMISSIONS = {
  dashboard: [ROLES.ADMIN, ROLES.MANAGER, ROLES.ENGINEER, ROLES.OPERATOR],
  devices: [ROLES.ADMIN, ROLES.MANAGER, ROLES.ENGINEER],
  alarms: [ROLES.ADMIN, ROLES.MANAGER, ROLES.ENGINEER],
  downtime: [ROLES.ADMIN, ROLES.MANAGER, ROLES.ENGINEER],
  analytics: [ROLES.ADMIN, ROLES.MANAGER, ROLES.ENGINEER],
  cameras: [ROLES.ADMIN, ROLES.MANAGER],
  reports: [ROLES.ADMIN, ROLES.MANAGER],
};
